name: firebase_image
description: A cached Flutter ImageProvider for Firebase Cloud Storage image objects.
version: 2.0.0
homepage: https://github.com/mattreid1/firebase_image

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  sqflite: ^2.2.8
  path: ^1.8.3
  path_provider: ^2.0.15

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
